FROM cgr.dev/chainguard/rust:latest-dev@sha256:951afe6f61f5d0200883e20f20f139172e38601f7d9ab4a3bf3a3828caa6a554 AS base

USER root
RUN apk update && apk --no-cache add \
    openssl-dev \
    perl \
    libsodium-dev

WORKDIR /usr/app

ARG CARGO_FEATURES=""

COPY . .
RUN if [ -n "$CARGO_FEATURES" ]; then \
      cargo install --root /usr/app --path . --locked --features "$CARGO_FEATURES"; \
    else \
      cargo install --root /usr/app --path . --locked; \
    fi

FROM cgr.dev/chainguard/wolfi-base

WORKDIR /app
COPY --from=base --chown=nonroot:nonroot /usr/app/bin/openzeppelin-relayer /app/openzeppelin-relayer
COPY --chown=nonroot:nonroot ./config /app/config
COPY --from=base /usr/lib/libssl.so.3 /usr/lib/libssl.so.3
COPY --from=base /usr/lib/libcrypto.so.3 /usr/lib/libcrypto.so.3

ARG TARGETARCH
ARG NODE_VERSION=20.19

USER root
RUN apk add --no-cache nodejs=~${NODE_VERSION} npm
ENV PATH="/usr/local/bin:$PATH"

RUN npm install -g pnpm ts-node typescript

COPY --chown=nonroot:nonroot ./plugins /app/plugins

USER nonroot
WORKDIR /app/plugins
RUN pnpm install --frozen-lockfile

WORKDIR /app

ENV APP_PORT=8080
ENV METRICS_PORT=8081

EXPOSE ${APP_PORT}/tcp ${METRICS_PORT}/tcp

ENTRYPOINT ["/app/openzeppelin-relayer"]